#!/usr/bin/env python
#
# Read a hex private key (64 digits) from stdin and output a WIF format version
#

import sys, binascii, hashlib

for line in sys.stdin:
	out = ""
	line = line[:64]
	alphabet="123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"
	chksum = binascii.hexlify(hashlib.sha256(hashlib.sha256(binascii.unhexlify('80'+line)).digest()).digest()[:4])
	bn = long('80'+line+chksum, 16)

	while bn >= 58:
		m = bn % 58
		out = alphabet[m] + out
		bn /= 58
	print alphabet[bn] + out



