#!/usr/bin/env python

import sys, binascii, hashlib

out = ""
alphabet="123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"
chksum = binascii.hexlify(hashlib.sha256(hashlib.sha256(binascii.unhexlify('80'+sys.argv[1])).digest()).digest()[:4])
bn = long('80'+sys.argv[1]+chksum, 16)

while bn >= 58:
	m = bn % 58
	out = alphabet[m] + out
	bn /= 58
print alphabet[bn] + out



